// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-qs5hDPZleu3Vfcja0subdXOKX0HYDr8',
    appId: '1:3806831661:web:bda05859a9abf836d704a4',
    messagingSenderId: '3806831661',
    projectId: 'mjcampusconnect',
    authDomain: 'mjcampusconnect.firebaseapp.com',
    storageBucket: 'mjcampusconnect.appspot.com',
    measurementId: 'G-8MXS811Z94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo-5M0YLbsTiIMRMioj0dfQCCyCnhUSJ8',
    appId: '1:3806831661:android:1c30bd67f7d4f9d8d704a4',
    messagingSenderId: '3806831661',
    projectId: 'mjcampusconnect',
    storageBucket: 'mjcampusconnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvbYWwu-RGeQ7hw7cpV_UPwOd5ty70qC4',
    appId: '1:3806831661:ios:9439b6efcba466d8d704a4',
    messagingSenderId: '3806831661',
    projectId: 'mjcampusconnect',
    storageBucket: 'mjcampusconnect.appspot.com',
    iosClientId: '3806831661-uahfs3ar2em92g7qtgdjitsc42au1df7.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );

}
